### ISSUE TITLE
Attempting to create a custom carrier but send() method not being invoked

### ISSUE THREAD

**Issue by pingleware** [BracketSpace/Notification-Extension-Boilerplate#10]
Attempting to create a custom carrier, but the send() method in the classes/Elements/Carrier/ExampleCarrier.php is NOT being invoked?

**Comment by Kubitomakita** [comment]
How do you test?

A couple of things to check:
- Is the notification being defined using this custom Carrier?
- Are you Triggering the notification?

**Comment by pingleware** [comment]
The suppress notifications was checked and doing as design by not invoking the send() method of the plugin. Cleared the checkbox, save and notification with a new carrier work. Will be submitting new carrier plugin to wordpress.org and bracketspace for integrating wordpress notifications with the Administrative Assistant at https://sourceforge.net/projects/administrative-assistant/.

**Comment by Kubitomakita** [comment]
That's awesome!
