### ISSUE TITLE
Without a single CI job this boilerplate is highly error prone

### ISSUE THREAD

**Issue by szepeviktor** [BracketSpace/Notification-Extension-Boilerplate#24]
Another thing: please make this repo a "template" in GitHub settings. e.g. https://github.com/szepeviktor/small-project

**Comment by Kubitomakita** [comment]
I was considering adding GitHub workflows but I decided it will be a call of plugin maintainer to include any jobs needed.

But thanks for the suggestion re template! I'm changing it now
